version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: notif
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./cmd/api
    environment:
      DATABASE_URL: postgres://notif:secret@postgres/notifications?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"

  push-worker:
    build: ./cmd/push-worker
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DATABASE_URL: postgres://notif:secret@postgres/notifications?sslmode=disable
    depends_on:
      - rabbitmq
      - postgres

  email-worker:
    build: ./cmd/email-worker
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DATABASE_URL: postgres://notif:secret@postgres/notifications?sslmode=disable
      SMTP_HOST: smtp.example.com
      SMTP_USER: user
      SMTP_PASS: pass
    depends_on:
      - rabbitmq
      - postgres

volumes:
  pgdata:
